#Requires -Version 5.1
# Initialize work/<case>/ with scope, timeline, workitems (reverse-skill ops contract).
# Bare invocation creates a draft scope.json and keeps offline defaults.
# Ready-to-act example:
#   powershell -File skills/scripts/case-init.ps1 -Hint "web pentest" -CaseName my-case `
#     -ScopeFile .\approved-scope.json -NetworkProfile authorized_target_only
param(
    [string] $Hint = '',
    [string] $CaseName = '',
    [string] $PackageRoot = '',
    [string] $ScopeFile = '',
    [switch] $AuthGranted,
    [string] $AuthStatus = '',
    [string] $AuthBasis = 'own_system',
    [string] $EvidenceOfAuth = '',
    [string] $TargetUrl = '',
    [string[]] $InScopeAssets = @(),
    [string] $NetworkProfile = '',
    [switch] $ReadyForAct
)
$ErrorActionPreference = 'Stop'

$scriptDir = $PSScriptRoot
if (-not $scriptDir) { $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path }
$skillsRoot = Split-Path -Parent $scriptDir
if (-not $PackageRoot) { $PackageRoot = Split-Path -Parent $skillsRoot }
$scopePolicyPath = Join-Path $scriptDir 'lib\ScopePolicy.ps1'
if (-not (Test-Path -LiteralPath $scopePolicyPath -PathType Leaf)) {
    throw "Scope policy module missing: $scopePolicyPath"
}
. $scopePolicyPath

if (-not $CaseName) {
    $slug = if ($Hint) {
        ($Hint.ToLowerInvariant() -replace '[^a-z0-9]+', '-').Trim('-')
    } else { 'case' }
    if ($slug.Length -gt 32) { $slug = $slug.Substring(0, 32).TrimEnd('-') }
    $CaseName = '{0}-{1}' -f (Get-Date -Format 'yyyyMMdd-HHmmss'), $slug
}

$caseRoot = Join-Path $PackageRoot ("work\{0}" -f $CaseName)
$dirs = @('evidence', 'notes', 'report')
New-Item -ItemType Directory -Force -Path $caseRoot | Out-Null
foreach ($d in $dirs) {
    New-Item -ItemType Directory -Force -Path (Join-Path $caseRoot $d) | Out-Null
}

# Resolve authorization only from an explicit scope.json. Journal text, hints,
# target arguments, AuthGranted, and ReadyForAct are never authorization evidence.
$scopeInput = $null
$scopeResult = $null
if (-not [string]::IsNullOrWhiteSpace($ScopeFile)) {
    $scopeResult = Import-ScopeDocument -Path $ScopeFile
    if ($scopeResult.Valid) {
        $scopeInput = $scopeResult.Scope
    } else {
        Write-Host ('WARN: supplied scope.json rejected: {0}' -f (($scopeResult.Issues) -join '; ')) -ForegroundColor Yellow
    }
}
if ($AuthGranted -and [string]::IsNullOrWhiteSpace($ScopeFile)) {
    Write-Host 'WARN: -AuthGranted is compatibility-only and requires a valid granted -ScopeFile; creating draft scope.' -ForegroundColor Yellow
}
if ($PSBoundParameters.ContainsKey('AuthStatus') -and -not [string]::IsNullOrWhiteSpace($AuthStatus)) {
    Write-Host 'WARN: -AuthStatus is compatibility-only; authorization comes only from scope.json.' -ForegroundColor Yellow
}

$explicitAssets = New-Object System.Collections.Generic.List[string]
if (-not [string]::IsNullOrWhiteSpace($TargetUrl)) { [void]$explicitAssets.Add($TargetUrl.Trim()) }
foreach ($asset in @($InScopeAssets)) {
    if (-not [string]::IsNullOrWhiteSpace($asset) -and -not $explicitAssets.Contains($asset.Trim())) {
        [void]$explicitAssets.Add($asset.Trim())
    }
}

function New-DraftScope {
    param([string[]] $AssetValues)
    $targets = New-Object System.Collections.Generic.List[object]
    foreach ($assetValue in @($AssetValues)) {
        try {
            [void]$targets.Add((ConvertTo-ScopeTarget -Value $assetValue))
        } catch {
            Write-Host ('WARN: ignoring invalid explicit target while creating draft: {0}' -f $assetValue) -ForegroundColor Yellow
        }
    }
    [pscustomobject]@{
        schemaVersion = '1'
        scopeId = ('draft-' + [guid]::NewGuid().ToString('n'))
        status = 'draft'
        approvalId = 'FILL_ME'
        issuedAt = (Get-Date).ToUniversalTime().ToString('o')
        expiresAt = (Get-Date).ToUniversalTime().AddHours(24).ToString('o')
        targets = $targets.ToArray()
        allowedActions = @()
        notes = 'Draft generated by case-init; user must provide an approved scope.json.'
    }
}

if ($null -eq $scopeInput) {
    $scopeInput = New-DraftScope -AssetValues @($explicitAssets)
}

$scopeValidation = Test-ScopeDocument -Scope $scopeInput
$scopeGrantedValidation = Test-ScopeDocument -Scope $scopeInput -RequireGranted
$scopeIsGranted = ($scopeValidation.Valid -and $scopeGrantedValidation.Valid -and [string]$scopeInput.status -eq 'granted')
if (-not $scopeValidation.Valid) {
    Write-Host ('WARN: generated scope is invalid and will remain blocked: {0}' -f (($scopeValidation.Issues) -join '; ')) -ForegroundColor Yellow
}
if ($scopeIsGranted -and $AuthGranted) {
    Write-Host 'INFO: -AuthGranted accepted only because the supplied scope.json is valid and granted.' -ForegroundColor DarkGray
}

$authStatusResolved = if ($scopeIsGranted) { 'granted' } else { [string]$scopeInput.status }
$evidenceAuth = if ($scopeIsGranted) { 'scope.json approvalId=' + [string]$scopeInput.approvalId } else { 'scope.json required' }

$assets = New-Object System.Collections.Generic.List[string]
foreach ($target in @($scopeInput.targets)) {
    if ([string]$target.type -eq 'network') {
        foreach ($prefix in @($target.pathPrefixes)) {
            [void]$assets.Add(('{0}://{1}:{2}{3}' -f $target.scheme, $target.host, $target.port, $prefix))
        }
    } elseif ([string]$target.type -eq 'file') {
        [void]$assets.Add([string]$target.path)
    }
}

$networkMode = 'offline'
if (-not [string]::IsNullOrWhiteSpace($NetworkProfile)) {
    $networkMode = $NetworkProfile.Trim()
} elseif ($scopeIsGranted -and @($scopeInput.targets | Where-Object { $_.type -eq 'network' }).Count -gt 0) {
    $networkMode = 'authorized_target_only'
}
$netAliases = @{
    'lab' = 'lab_only'
    'authorized' = 'authorized_target_only'
    'auth' = 'authorized_target_only'
    'offline_only' = 'offline'
}
if ($netAliases.ContainsKey($networkMode.ToLowerInvariant())) { $networkMode = $netAliases[$networkMode.ToLowerInvariant()] }
if (-not $scopeIsGranted) { $networkMode = 'offline' }

# ready_for_act requires a valid granted scope and explicit targets. Network
# targets additionally require a non-offline network profile; exact file scopes
# remain usable in offline mode.
$ready = $false
$hasNetworkTargets = @($scopeInput.targets | Where-Object { $_.type -eq 'network' }).Count -gt 0
$hasFileTargets = @($scopeInput.targets | Where-Object { $_.type -eq 'file' }).Count -gt 0
$netAllowsAct = ($networkMode -ne 'offline' -and -not [string]::IsNullOrWhiteSpace($networkMode))
if ($scopeIsGranted -and $assets.Count -gt 0 -and (($hasNetworkTargets -and $netAllowsAct) -or ($hasFileTargets -and -not $hasNetworkTargets))) { $ready = $true }
if ($ReadyForAct -and -not $ready) {
    Write-Host 'WARN: -ReadyForAct cannot override scope.json validation or authorization.' -ForegroundColor Yellow
}

# Optional master-route for primary skill
$primary = 'reverse-engineering/SKILL.md'
$primaryId = 'R0'
$routeScript = Join-Path $scriptDir 'master-route.ps1'
if ((Test-Path $routeScript) -and $Hint) {
    $tmp = Join-Path $env:TEMP ("case-init-route-" + [guid]::NewGuid().ToString('n'))
    try {
        & powershell -NoProfile -ExecutionPolicy Bypass -File $routeScript -Hint $Hint -OutDir $tmp 2>$null | Out-Null
        $scopeRoute = Join-Path $tmp 'route-scope.md'
        if (Test-Path $scopeRoute) {
            $rt = Get-Content $scopeRoute -Raw -Encoding UTF8
            if ($rt -match 'primary_skill:\s*skills/(\S+)') { $primary = $Matches[1] }
            if ($rt -match 'primary:\s*(\S+)') { $primaryId = $Matches[1] }
        }
    } finally {
        Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue
    }
}

$created = Get-Date -Format 'o'
if ($assets.Count -gt 0) {
    $assetsBlock = ($assets | ForEach-Object { "  - $_" }) -join [Environment]::NewLine
} else {
    $assetsBlock = '  []'
}

$checkAuth = if ($authStatusResolved -eq 'granted') { '[x]' } else { '[ ]' }
$checkScope = if ($assets.Count -gt 0) { '[x]' } else { '[ ]' }
$checkNet = if (($hasNetworkTargets -and $netAllowsAct) -or ($hasFileTargets -and $networkMode -eq 'offline')) { '[x]' } else { '[ ]' }
$readyStr = if ($ready) { 'true' } else { 'false' }
$timelineNext = if ($ready) {
    'open PRIMARY SKILL.md and ACT within scope'
} else {
    'supply a valid user-approved scope.json; scope.md is read-only derived output'
}
$timelineSummary = if ($ready) {
    'case directory created; scope ready_for_act=true'
} else {
    'case directory created; scope pending auth'
}

$scope = @"
# Case Scope

## meta
- case_id: $CaseName
- created: $created
- operator: local
- primary_skill: $primary
- primary_id: $primaryId
- lead_role: lead
- specialist_roles: []
- hint: $Hint

## auth
- status: $authStatusResolved
- source_of_truth: scope.json
- scope_id: $($scopeInput.scopeId)
- approval_id: $($scopeInput.approvalId)
- legacy_basis_note: $AuthBasis
- evidence_of_auth: $evidenceAuth
- scope.md is derived and cannot grant authorization
- MUST NOT proceed if scope.json status != granted

## in_scope
- assets:
$assetsBlock
- surfaces: []
- activities: []

## out_of_scope
- assets: []
- activities: [dos, phishing_real_users, unrestricted_exfil]

## network_profile
- mode: $networkMode
- notes: |
    offline | lab_only | authorized_target_only | unrestricted_lab
    Network execution also requires a valid granted scope.json target.

## deliverables
- report: true
- field_journal: true
- diagrams: true
- timeline: true

## constraints
- timebox: {}
- stealth: low
- data_handling: anonymize

## signoff
- ready_for_act: $readyStr
- checklist:
  - $checkAuth scope.json status = granted and unexpired
  - $checkScope in_scope.assets non-empty OR offline sample path set
  - $checkNet network_profile.mode chosen
  - [ ] out_of_scope reviewed
  - [ ] roles assigned (see skills/ops/role-map.md)

## ops_refs
- skills/ops/scope-contract.md
- skills/ops/evidence-finding-path.md
- skills/ops/role-map.md
- skills/ops/timeline-workitem.md
- skills/ops/IDENTITY.md
"@

$timeline = @"
# Timeline (append-only)

## $created | lead | init
- action: case-init
- command_or_ref: skills/scripts/case-init.ps1
- result_summary: $timelineSummary
- artifacts: [scope.json, scope.md, workitems.md]
- evidence_ids: []
- next: $timelineNext
"@

$workitems = @"
# Work Items

| ID | title | role | targets | surface | status | evidence | notes |
|----|-------|------|---------|---------|--------|----------|-------|
| WI-001 | Establish scope and auth | lead | case | process | in_progress | | |

## Coverage
- [ ] Recon/analysis complete for in_scope assets
- [ ] Critical/High candidates triaged (or N/A for pure RE)
- [ ] Validated findings have Evidence (E-*)
- [ ] Path documented (attack/call/solve)
- [ ] Timeline continuous across major phases
- [ ] Report via docs-generator
- [ ] field-journal anonymized

## Refs
- skills/ops/timeline-workitem.md
- skills/ops/evidence-finding-path.md
"@

$utf8 = New-Object System.Text.UTF8Encoding $true
$scopeJson = $scopeInput | ConvertTo-Json -Depth 8
[System.IO.File]::WriteAllText((Join-Path $caseRoot 'scope.json'), $scopeJson + [Environment]::NewLine, $utf8)
[System.IO.File]::WriteAllText((Join-Path $caseRoot 'scope.md'), $scope, $utf8)
[System.IO.File]::WriteAllText((Join-Path $caseRoot 'timeline.md'), $timeline, $utf8)
[System.IO.File]::WriteAllText((Join-Path $caseRoot 'workitems.md'), $workitems, $utf8)

$readmeNext = if ($ready) {
    @"
1. Scope is ready_for_act=true (auth granted + in_scope set)
2. Open primary skill: skills/$primary
3. Append ``timeline.md``; update ``workitems.md``
4. Append Evidence: ``skills/scripts/append-evidence.ps1 -CaseRoot <this dir> ...``
5. Promote findings with Evidence chain (skills/ops/evidence-finding-path.md)
6. Report via docs-generator; journal via field-journal
"@
} else {
    @"
1. Obtain a user-provided ``scope.json`` with target, actions, approval ID, and expiry
2. Re-run ``case-init.ps1 -ScopeFile <approved-scope.json>``
3. Treat ``scope.md`` as derived read-only output; editing it never grants authorization
4. Open primary skill: skills/$primary only after ``case-guard.ps1`` succeeds
5. Append ``timeline.md``; update ``workitems.md``
6. Report via docs-generator; journal via field-journal
"@
}

$readme = @"
# Case $CaseName

$readmeNext
"@
[System.IO.File]::WriteAllText((Join-Path $caseRoot 'README.md'), $readme, $utf8)

Write-Host ("CASE -> {0}" -f $caseRoot) -ForegroundColor Green
Write-Host ("PRIMARY skill: skills/{0} ({1})" -f $primary, $primaryId)
Write-Host ("auth.status={0} network_profile={1} ready_for_act={2}" -f $authStatusResolved, $networkMode, $readyStr)
if ($ready) {
    Write-Host 'NEXT: open PRIMARY SKILL.md and ACT within scope' -ForegroundColor Green
} else {
    Write-Host 'NEXT: provide a valid approved scope.json; editing scope.md cannot grant authorization'
}
